package com.google.android.gms.internal.ads;

import android.content.Context;
import android.content.SharedPreferences;
import androidx.recyclerview.widget.ItemTouchHelper;
import androidx.vectordrawable.graphics.drawable.PathInterpolatorCompat;
import com.google.android.gms.ads.RequestConfiguration;
import java.util.List;
import java.util.concurrent.TimeUnit;
import org.json.JSONObject;
/* compiled from: com.google.android.gms:play-services-ads-lite@@20.2.0 */
/* loaded from: classes.dex */
public final class zzbfq {
    public static final zzbfi<String> zza = zzbfi.zzk(1, "gads:sdk_core_location:client:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final zzbfi<String> zzb = zzbfi.zzk(1, "gads:active_view_location:html", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/sdk-core-v40-impl.html");
    public static final zzbgs<Boolean> zzc = zzbhg.zzd;
    public static final zzbfi<Integer> zzd = zzbfi.zzh(1, "gads:http_url_connection_factory:timeout_millis", 10000);
    public static final zzbfi<String> zze = zzbfi.zzk(1, "gads:video_exo_player:version", "3");
    public static final zzbfi<Integer> zzf = zzbfi.zzh(1, "gads:video_exo_player:connect_timeout", 8000);
    public static final zzbfi<Integer> zzg = zzbfi.zzh(1, "gads:video_exo_player:read_timeout", 8000);
    public static final zzbfi<Integer> zzh = zzbfi.zzh(1, "gads:video_exo_player:loading_check_interval", 1048576);
    public static final zzbfi<Integer> zzi = zzbfi.zzh(1, "gads:video_exo_player:exo_player_precache_limit", Integer.MAX_VALUE);
    public static final zzbfi<Integer> zzj = zzbfi.zzh(1, "gads:video_exo_player:byte_buffer_precache_limit", Integer.MAX_VALUE);
    public static final zzbfi<Integer> zzk = zzbfi.zzh(1, "gads:video_exo_player_socket_receive_buffer_size", 0);
    public static final zzbfi<Integer> zzl = zzbfi.zzh(1, "gads:video_exo_player:min_retry_count", -1);
    public static final zzbfi<Boolean> zzm = new zzbfd(1, "gads:video_exo_player:fmp4_extractor_enabled", true);
    public static final zzbfi<Boolean> zzn = new zzbfd(1, "gads:video_exo_player:use_play_back_info_for_should_start_play_back", false);
    public static final zzbfi<Boolean> zzo = new zzbfd(1, "gads:video_exo_player:treat_load_exception_as_non_fatal", true);
    public static final zzbfi<Integer> zzp = zzbfi.zzh(1, "gads:video_stream_cache:limit_count", 5);
    public static final zzbfi<Integer> zzq = zzbfi.zzh(1, "gads:video_stream_cache:limit_space", 8388608);
    public static final zzbfi<Integer> zzr = zzbfi.zzh(1, "gads:video_stream_exo_cache:buffer_size", 8388608);
    public static final zzbfi<Long> zzs = zzbfi.zzi(1, "gads:video_stream_cache:limit_time_sec", 300);
    public static final zzbfi<Long> zzt = zzbfi.zzi(1, "gads:video_stream_cache:notify_interval_millis", 125);
    public static final zzbfi<Integer> zzu = zzbfi.zzh(1, "gads:video_stream_cache:connect_timeout_millis", 10000);
    public static final zzbfi<String> zzv = zzbfi.zzk(1, "gads:video:metric_frame_hash_times", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Long> zzw = zzbfi.zzi(1, "gads:video:metric_frame_hash_time_leniency", 500);
    public static final zzbfi<Boolean> zzx = new zzbfd(1, "gads:video:force_watermark", false);
    public static final zzbfi<Long> zzy = zzbfi.zzi(1, "gads:video:surface_update_min_spacing_ms", 1000);
    public static final zzbfi<Boolean> zzz = new zzbfd(1, "gads:video:spinner:enabled", false);
    public static final zzbfi<Boolean> zzA = new zzbfd(1, "gads:video:shutter:enabled", false);
    public static final zzbfi<Integer> zzB = zzbfi.zzh(1, "gads:video:spinner:scale", 4);
    public static final zzbfi<Long> zzC = zzbfi.zzi(1, "gads:video:spinner:jank_threshold_ms", 50);
    public static final zzbfi<Boolean> zzD = new zzbfd(1, "gads:video:aggressive_media_codec_release", false);
    public static final zzbfi<Boolean> zzE = new zzbfd(1, "gads:memory_bundle:debug_info", false);
    public static final zzbfi<String> zzF = zzbfi.zzk(1, "gads:video:codec_query_mime_types", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Integer> zzG = zzbfi.zzh(1, "gads:video:codec_query_minimum_version", 16);
    public static final zzbfi<String> zzH = zzbfi.zzk(1, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_banner.js");
    public static final zzbfi<String> zzI = zzbfi.zzk(1, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_expanded_banner.js");
    public static final zzbfi<String> zzJ = zzbfi.zzk(1, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/production/mraid/v3/mraid_app_interstitial.js");
    public static final zzbfi<String> zzK = zzbfi.zzk(1, "gad:mraid:version", "3.0");
    public static final zzbfi<Boolean> zzL = new zzbfd(1, "gads:mraid:expanded_interstitial_fix", false);
    public static final zzbfi<Boolean> zzM = new zzbfd(1, "gads:mraid:initial_size_fallback", false);
    public static final zzbfi<Integer> zzN = zzbfi.zzh(1, "gads:content_vertical_fingerprint_number", 100);
    public static final zzbfi<Integer> zzO = zzbfi.zzh(1, "gads:content_vertical_fingerprint_bits", 23);
    public static final zzbfi<Integer> zzP = zzbfi.zzh(1, "gads:content_vertical_fingerprint_ngram", 3);
    public static final zzbfi<String> zzQ = zzbfi.zzk(1, "gads:content_fetch_view_tag_id", "googlebot");
    public static final zzbfi<String> zzR = zzbfi.zzk(1, "gads:content_fetch_exclude_view_tag", "none");
    public static final zzbfi<Boolean> zzS = new zzbfd(1, "gads:content_fetch_disable_get_title_from_webview", false);
    public static final zzbfi<Boolean> zzT = new zzbfd(1, "gads:content_fetch_enable_new_content_score", false);
    public static final zzbfi<Boolean> zzU = new zzbfd(1, "gads:content_fetch_enable_serve_once", false);
    public static final zzbfi<Boolean> zzV = new zzbfd(1, "gads:sai:enabled", true);
    public static final zzbfi<String> zzW = zzbfi.zzk(1, "gads:sai:click_ping_schema_v2", "^[^?]*(/aclk\\?|/pcs/click\\?).*");
    public static final zzbfi<String> zzX = zzbfi.zzk(1, "gads:sai:impression_ping_schema_v2", "^[^?]*(/adview|/pcs/view).*");
    public static final zzbfi<Boolean> zzY = new zzbfd(1, "gads:sai:using_macro:enabled", false);
    public static final zzbfi<String> zzZ = zzbfi.zzk(1, "gads:sai:ad_event_id_macro_name", "[gw_fbsaeid]");
    public static final zzbfi<Long> zzaa = zzbfi.zzi(1, "gads:sai:timeout_ms", -1);
    public static final zzbfi<Integer> zzab = zzbfi.zzh(1, "gads:sai:scion_thread_pool_size", 5);
    public static final zzbfi<Boolean> zzac = new zzbfd(1, "gads:sai:app_measurement_enabled3", false);
    public static final zzbfi<Integer> zzad = zzbfi.zzh(1, "gads:sai:app_measurement_min_client_dynamite_version", 20290);
    public static final zzbfi<Boolean> zzae = new zzbfd(1, "gads:sai:force_through_reflection", true);
    public static final zzbfi<Boolean> zzaf = new zzbfd(1, "gads:sai:gmscore_availability_check_disabled", false);
    public static final zzbfi<Boolean> zzag = new zzbfd(1, "gads:sai:logging_disabled_for_drx", false);
    public static final zzbfi<Boolean> zzah = new zzbfd(1, "gads:sai:app_measurement_npa_enabled", false);
    public static final zzbfi<Boolean> zzai = new zzbfd(1, "gads:idless:idless_disables_attestation", true);
    public static final zzbfi<Boolean> zzaj = new zzbfd(1, "gads:idless:app_measurement_idless_enabled", true);
    public static final zzbfi<Boolean> zzak = new zzbfd(1, "gads:sai:server_side_npa:disable_writing", false);
    public static final zzbfi<Boolean> zzal = new zzbfd(1, "gads:sai:server_side_npa:enabled", false);
    public static final zzbfi<Long> zzam = zzbfi.zzi(1, "gads:sai:server_side_npa:ttl", TimeUnit.DAYS.toMillis(90));
    public static final zzbfi<String> zzan = zzbfi.zzk(1, "gads:sai:server_side_npa:shared_preference_key_list", "{  \"__default__\": [    \"IABTCF_TCString\"  ],  \"mobileads_consent\": [    \"consent_string\"  ]}");
    public static final zzbfi<Boolean> zzao = new zzbfd(1, "gads:idless:internal_state_enabled", true);
    public static final zzbfi<Boolean> zzap = new zzbfd(1, "gads:idless:idless_disables_offline_ads_signalling", true);
    public static final zzbfi<String> zzaq = zzbfi.zzk(1, "gads:idless:cookie_modification", "=; Max-Age=-1; path=/; domain=.doubleclick.net");
    public static final zzbfi<Boolean> zzar = new zzbfd(1, "gads:interstitial:app_must_be_foreground:enabled", false);
    public static final zzbfi<Boolean> zzas = new zzbfd(1, "gads:interstitial:foreground_report:enabled", false);
    public static final zzbfi<Boolean> zzat = new zzbfd(1, "gads:interstitial:default_immersive", false);
    public static final zzbfi<Integer> zzau = zzbfi.zzh(1, "gads:show_interstitial_with_context:min_version", 999999999);
    public static final zzbfi<Boolean> zzav = new zzbfd(1, "gads:webview:error_web_response:enabled", false);
    public static final zzbfi<Boolean> zzaw = new zzbfd(1, "gads:webview:set_fixed_text_zoom", false);
    public static final zzbfi<Boolean> zzax = new zzbfd(1, "gads:webviewgone:kill_process:enabled", false);
    public static final zzbfi<Boolean> zzay = new zzbfd(1, "gads:webviewgone:new_onshow:enabled", false);
    public static final zzbfi<String> zzaz = zzbfi.zzk(1, "gads:webview_cookie_url", "googleads.g.doubleclick.net");
    public static final zzbfi<Boolean> zzaA = new zzbfd(1, "gads:new_rewarded_ad:enabled", true);
    public static final zzbfi<Boolean> zzaB = new zzbfd(1, "gads:rewarded:adapter_initialization_enabled", false);
    public static final zzbfi<Boolean> zzaC = new zzbfd(1, "gads:rewarded:ad_metadata_enabled", false);
    public static final zzbfi<Long> zzaD = zzbfi.zzi(1, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500);
    public static final zzbfi<Long> zzaE = zzbfi.zzi(1, "gads:app_activity_tracker:app_session_timeout_ms", TimeUnit.MINUTES.toMillis(5));
    public static final zzbfi<Boolean> zzaF = new zzbfd(1, "gads:adid_values_in_adrequest:enabled", false);
    public static final zzbfi<Long> zzaG = zzbfi.zzi(1, "gads:adid_values_in_adrequest:timeout", 2000);
    public static final zzbfi<Boolean> zzaH = new zzbfd(1, "gads:disable_adid_values_in_ms", false);
    public static final zzbfi<Long> zzaI = zzbfi.zzi(1, "gads:ad_overlay:delay_page_close_timeout_ms", 5000);
    public static final zzbfi<Boolean> zzaJ = new zzbfd(1, "gads:custom_close_blocking:enabled", false);
    public static final zzbfi<Boolean> zzaK = new zzbfd(1, "gads:disabling_closable_area:enabled", false);
    public static final zzbfi<Boolean> zzaL = new zzbfd(1, "gads:use_system_ui_for_fullscreen:enabled", false);
    public static final zzbfi<Boolean> zzaM = new zzbfd(1, "gads:ad_overlay:collect_cutout_info:enabled", false);
    public static final zzbfi<String> zzaN = zzbfi.zzk(1, "gads:spherical_video:vertex_shader", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<String> zzaO = zzbfi.zzk(1, "gads:spherical_video:fragment_shader", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Boolean> zzaP = new zzbfd(1, "gads:include_local_global_rectangles", false);
    public static final zzbfi<Long> zzaQ = zzbfi.zzi(1, "gads:position_watcher:throttle_ms", 200);
    public static final zzbfi<Long> zzaR = zzbfi.zzi(1, "gads:position_watcher:scroll_aware_throttle_ms", 33);
    public static final zzbfi<Boolean> zzaS = new zzbfd(1, "gads:position_watcher:enable_scroll_aware_ads", false);
    public static final zzbfi<Boolean> zzaT = new zzbfd(1, "gads:position_watcher:send_scroll_data", false);
    public static final zzbfi<Boolean> zzaU = new zzbfd(1, "gads:gen204_signals:enabled", false);
    public static final zzbfi<Boolean> zzaV = new zzbfd(1, "gads:extra_sdk_versions_for_crash_reports:enabled", true);
    public static final zzbfi<String> zzaW = zzbfi.zzk(1, "gads:logged_adapter_version_classes", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Long> zzaX = zzbfi.zzi(1, "gads:rtb_v1_1:signal_timeout_ms", 1000);
    public static final zzbfi<String> zzaY = zzbfi.zzk(1, "gads:rtb_logging:regex", "(?!)");
    public static final zzbfi<Boolean> zzaZ = new zzbfd(1, "gads:presentation_error:urls_enabled", true);
    public static final zzbfi<Boolean> zzba = new zzbfd(1, "gads:rtb_interstitial:use_fullscreen_monitor", true);
    public static final zzbfi<Boolean> zzbb = new zzbfd(1, "gads:native_required_assets:enabled", false);
    public static final zzbfi<Boolean> zzbc = new zzbfd(1, "gads:native_required_assets:check_inner_mediaview:enabled", true);
    public static final zzbfi<Integer> zzbd = zzbfi.zzh(1, "gads:native_ad_options_rtb:min_version", 999999999);
    public static final zzbfi<Boolean> zzbe = new zzbfd(1, "gads:track_view_next_runloop:enabled", false);
    public static final zzbfi<Boolean> zzbf = new zzbfd(1, "gads:native_required_assets:viewability:enabled", false);
    public static final zzbfi<Integer> zzbg = zzbfi.zzh(1, "gads:adapter_initialization:min_sdk_version", 15301000);
    public static final zzbfi<Long> zzbh = zzbfi.zzi(1, "gads:adapter_initialization:timeout", 30);
    public static final zzbfi<Long> zzbi = zzbfi.zzi(1, "gads:adapter_initialization:cld_timeout", 10);
    public static final zzbfi<Boolean> zzbj = new zzbfd(1, "gads:additional_video_csi:enabled", false);
    public static final zzbfi<Boolean> zzbk = new zzbfd(1, "gads:using_official_exoplayer:enabled", false);
    public static final zzbfi<Boolean> zzbl = new zzbfd(1, "gads:csi:enabled_per_sampling", false);
    public static final zzbfi<Boolean> zzbm = new zzbfd(1, "gads:always_set_transfer_listener:enabled", false);
    public static final zzbfi<Boolean> zzbn = new zzbfd(1, "gads:initialization_csi:enabled", false);
    public static final zzbfi<Boolean> zzbo = new zzbfd(1, "gads:msa:experiments:enabled", false);
    public static final zzbfi<Boolean> zzbp = new zzbfd(1, "gads:msa:experiments:ps:enabled", false);
    public static final zzbfi<Boolean> zzbq = new zzbfd(1, "gads:msa:experiments:fb:enabled", true);
    public static final zzbfi<Boolean> zzbr = new zzbfd(1, "gads:msa:experiments:ps:er", true);
    public static final zzbfi<Integer> zzbs = zzbfi.zzh(1, "gads:gestures:a2:enabled", 0);
    public static final zzbfi<Boolean> zzbt = new zzbfd(1, "gads:msa:experiments:a2", false);
    public static final zzbfi<Boolean> zzbu = new zzbfd(1, "gads:msa:experiments:log", true);
    public static final zzbfi<Boolean> zzbv = new zzbfd(1, "gads:msa:experiments:vfb", true);
    public static final zzbfi<Boolean> zzbw = new zzbfd(1, "gads:msa:experiments:incapi:enabled", false);
    public static final zzbfi<String> zzbx = zzbfi.zzk(1, "gads:msa:experiments:incapi:trusted_cert", "308204433082032ba003020102020900c2e08746644a308d300d06092a864886f70d01010405003074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964301e170d3038303832313233313333345a170d3336303130373233313333345a3074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f696430820120300d06092a864886f70d01010105000382010d00308201080282010100ab562e00d83ba208ae0a966f124e29da11f2ab56d08f58e2cca91303e9b754d372f640a71b1dcb130967624e4656a7776a92193db2e5bfb724a91e77188b0e6a47a43b33d9609b77183145ccdf7b2e586674c9e1565b1f4c6a5955bff251a63dabf9c55c27222252e875e4f8154a645f897168c0b1bfc612eabf785769bb34aa7984dc7e2ea2764cae8307d8c17154d7ee5f64a51a44a602c249054157dc02cd5f5c0e55fbef8519fbe327f0b1511692c5a06f19d18385f5c4dbc2d6b93f68cc2979c70e18ab93866b3bd5db8999552a0e3b4c99df58fb918bedc182ba35e003c1b4b10dd244a8ee24fffd333872ab5221985edab0fc0d0b145b6aa192858e79020103a381d93081d6301d0603551d0e04160414c77d8cc2211756259a7fd382df6be398e4d786a53081a60603551d2304819e30819b8014c77d8cc2211756259a7fd382df6be398e4d786a5a178a4763074310b3009060355040613025553311330110603550408130a43616c69666f726e6961311630140603550407130d4d6f756e7461696e205669657731143012060355040a130b476f6f676c6520496e632e3110300e060355040b1307416e64726f69643110300e06035504031307416e64726f6964820900c2e08746644a308d300c0603551d13040530030101ff300d06092a864886f70d010104050003820101006dd252ceef85302c360aaace939bcff2cca904bb5d7a1661f8ae46b2994204d0ff4a68c7ed1a531ec4595a623ce60763b167297a7ae35712c407f208f0cb109429124d7b106219c084ca3eb3f9ad5fb871ef92269a8be28bf16d44c8d9a08e6cb2f005bb3fe2cb96447e868e731076ad45b33f6009ea19c161e62641aa99271dfd5228c5c587875ddb7f452758d661f6cc0cccb7352e424cc4365c523532f7325137593c4ae341f4db41edda0d0b1071a7c440f0fe9ea01cb627ca674369d084bd2fd911ff06cdbf2cfa10dc0f893ae35762919048c7efc64c7144178342f70581c9de573af55b390dd7fdb9418631895d5f759f30112687ff621410c069308a");
    public static final zzbfi<Boolean> zzby = new zzbfd(1, "gads:gestures:clearTd:enabled", false);
    public static final zzbgs<Boolean> zzbz = zzbhf.zzb;
    public static final zzbfi<Boolean> zzbA = new zzbfd(1, "gads:gestures:errorlogging:enabled", false);
    public static final zzbfi<Long> zzbB = zzbfi.zzi(1, "gads:gestures:task_timeout", 2000);
    public static final zzbfi<Boolean> zzbC = new zzbfd(1, "gads:gestures:asig:enabled", false);
    public static final zzbfi<Boolean> zzbD = new zzbfd(1, "gads:gestures:ans:enabled", false);
    public static final zzbfi<Boolean> zzbE = new zzbfd(1, "gads:gestures:tos:enabled", false);
    public static final zzbfi<Boolean> zzbF = new zzbfd(1, "gads:gestures:brt:enabled", true);
    public static final zzbfi<Boolean> zzbG = new zzbfd(1, "gads:gestures:fpi:enabled", false);
    public static final zzbfi<Boolean> zzbH = new zzbfd(1, "gads:signal:app_permissions:disabled", false);
    public static final zzbfi<Boolean> zzbI = new zzbfd(1, "gads:gestures:hpk:enabled", true);
    public static final zzbfi<String> zzbJ = zzbfi.zzk(1, "gads:gestures:pk", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Boolean> zzbK = zzbfi.zzg(1, "gads:gestures:bs:enabled", true);
    public static final zzbfi<Boolean> zzbL = zzbfi.zzg(1, "gads:gestures:check_initialization_thread:enabled", false);
    public static final zzbfi<Boolean> zzbM = zzbfi.zzg(1, "gads:gestures:init_new_thread:enabled", true);
    public static final zzbfi<Boolean> zzbN = zzbfi.zzg(1, "gads:gestures:pds:enabled", true);
    public static final zzbfi<Integer> zzbO = zzbfi.zzh(1, "gads:gestures:as2percentage", 0);
    public static final zzbfi<Boolean> zzbP = zzbfi.zzg(1, "gads:gestures:ns:enabled", true);
    public static final zzbfi<Boolean> zzbQ = zzbfi.zzg(1, "gads:gestures:vdd:enabled", false);
    public static final zzbfi<Boolean> zzbR = zzbfi.zzg(1, "gads:native:asset_view_touch_events", false);
    public static final zzbfi<Boolean> zzbS = zzbfi.zzg(1, "gads:native:set_touch_listener_on_asset_views", true);
    public static final zzbfi<Boolean> zzbT = zzbfi.zzg(1, "gads:ais:enabled", true);
    public static final zzbfi<Boolean> zzbU = zzbfi.zzg(1, "gads:stav:enabled", false);
    public static final zzbfi<Boolean> zzbV = zzbfi.zzg(1, "gads:spam:impression_ui_idle:enable", false);
    public static final zzbfi<String> zzbW = zzbfi.zzl(1, "gads:sdk_core_constants:experiment_id");
    public static final zzbfi<String> zzbX = zzbfi.zzk(1, "gads:sdk_core_constants:caps", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Boolean> zzbY = zzbfi.zzg(1, "gads:js_flags:disable_phenotype", false);
    public static final zzbfi<String> zzbZ = zzbfi.zzk(1, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    public static final zzbfi<String> zzca = zzbfi.zzk(1, "gads:native:video_url_with_protocol", "https://imasdk.googleapis.com/admob/sdkloader/native_video.html");
    public static final zzbfi<Boolean> zzcb = zzbfi.zzg(1, "gads:native:get_native_ad_view_signals", false);
    public static final zzbfi<Integer> zzcc = zzbfi.zzh(1, "gads:native_video_load_timeout", 10);
    public static final zzbfi<Boolean> zzcd = zzbfi.zzg(1, "gads:omid:native_video_ad_user_action_event:enabled", false);
    public static final zzbfi<String> zzce = zzbfi.zzk(1, "gads:ad_choices_content_description", "Ad Choices Icon");
    public static final zzbfi<Boolean> zzcf = zzbfi.zzg(1, "gads:enable_singleton_broadcast_receiver", false);
    public static final zzbfi<Boolean> zzcg = zzbfi.zzg(1, "gads:native:media_view_match_parent:enabled", true);
    public static final zzbfi<Boolean> zzch = zzbfi.zzg(1, "gads:video:restrict_inside_web_view:enabled", false);
    public static final zzbfi<Boolean> zzci = zzbfi.zzg(1, "gads:native:count_impression_for_assets", false);
    public static final zzbfi<Boolean> zzcj = zzbfi.zzg(1, "gads:fluid_ad:use_wrap_content_height", false);
    public static final zzbfi<Boolean> zzck = zzbfi.zzg(1, "gads:rtb_v1_1:fetch_app_settings_using_cld:enabled", true);
    public static final zzbfi<Boolean> zzcl = zzbfi.zzg(1, "gads:get_request_signals_cld:enabled", true);
    public static final zzbfi<Boolean> zzcm = zzbfi.zzg(1, "gads:get_request_signals_common_cld:enabled", true);
    public static final zzbfi<Boolean> zzcn = zzbfi.zzg(1, "gads:rtb_v1_1:use_manifest_appid_cld:enabled", true);
    public static final zzbfi<Long> zzco = zzbfi.zzi(1, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000);
    public static final zzbfi<Long> zzcp = zzbfi.zzi(1, "gads:parental_controls:timeout", 2000);
    public static final zzbfi<Integer> zzcq = zzbfi.zzh(1, "gads:cache:ad_request_timeout_millis", ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    public static final zzbfi<Integer> zzcr = zzbfi.zzh(1, "gads:cache:max_concurrent_downloads", 10);
    public static final zzbfi<Boolean> zzcs = zzbfi.zzg(1, "gads:cache:downloader_use_high_priority", false);
    public static final zzbfi<Long> zzct = zzbfi.zzi(1, "gads:cache:javascript_timeout_millis", 5000);
    public static final zzbfi<Boolean> zzcu = zzbfi.zzg(1, "gads:cache:bind_on_foreground", false);
    public static final zzbfi<Boolean> zzcv = zzbfi.zzg(1, "gads:cache:bind_on_init", false);
    public static final zzbfi<Boolean> zzcw = zzbfi.zzg(1, "gads:cache:bind_on_request", false);
    public static final zzbfi<Long> zzcx = zzbfi.zzi(1, "gads:cache:bind_on_request_keep_alive", TimeUnit.SECONDS.toMillis(30));
    public static final zzbfi<Boolean> zzcy = zzbfi.zzg(1, "gads:cache:use_cache_data_source", false);
    public static final zzbfi<Boolean> zzcz = zzbfi.zzg(1, "gads:cache:connection_per_read", false);
    public static final zzbfi<Long> zzcA = zzbfi.zzi(1, "gads:cache:connection_timeout", 5000);
    public static final zzbfi<Long> zzcB = zzbfi.zzi(1, "gads:cache:read_only_connection_timeout", 5000);
    public static final zzbfi<Boolean> zzcC = zzbfi.zzg(1, "gads:cache:read_inner_data_source_if_gcache_miss", false);
    public static final zzbfi<Boolean> zzcD = zzbfi.zzg(1, "gads:cache:read_inner_data_source_if_gcache_not_downloaded", false);
    public static final zzbfi<Boolean> zzcE = zzbfi.zzg(1, "gads:cache:function_call_timeout_v1:enabled", false);
    public static final zzbfi<Long> zzcF = zzbfi.zzi(1, "gads:cache:function_call_timeout", 5000);
    public static final zzbfi<Boolean> zzcG = zzbfi.zzg(1, "gads:http_assets_cache:enabled", false);
    public static final zzbfi<String> zzcH = zzbfi.zzk(1, "gads:http_assets_cache:regex", "(?i)https:\\/\\/(tpc\\.googlesyndication\\.com\\/(.*)|lh\\d+\\.googleusercontent\\.com\\/(.*))");
    public static final zzbfi<Integer> zzcI = zzbfi.zzh(1, "gads:http_assets_cache:time_out", 100);
    public static final zzbfi<Boolean> zzcJ = zzbfi.zzg(1, "gads:chrome_custom_tabs_browser:enabled", false);
    public static final zzbfi<Boolean> zzcK = zzbfi.zzg(1, "gads:chrome_custom_tabs:disabled", false);
    public static final zzbfi<Boolean> zzcL = zzbfi.zzg(1, "gads:chrome_custom_tabs_browser_v2:enabled", false);
    public static final zzbfi<Boolean> zzcM = zzbfi.zzg(1, "gads:cct_v2_connection:enabled", false);
    public static final zzbfi<Boolean> zzcN = zzbfi.zzg(1, "gads:cct_v2_direct_launch:enabled", false);
    public static final zzbfi<Boolean> zzcO = zzbfi.zzg(1, "gads:chrome_custom_tabs_for_native_ads:enabled", false);
    public static final zzbfi<Boolean> zzcP = zzbfi.zzg(1, "gad:cct_v2_beta:enabled", false);
    public static final zzbfi<String> zzcQ = zzbfi.zzk(1, "gad:publisher_testing:cct_v2:enabled_list", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Boolean> zzcR = zzbfi.zzg(2, "CHROME_CUSTOM_TAB_OPT_OUT", false);
    public static final zzbfi<Long> zzcS = zzbfi.zzi(1, "gads:debug_hold_gesture:time_millis", 2000);
    public static final zzbfi<String> zzcT = zzbfi.zzk(1, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    public static final zzbfi<String> zzcU = zzbfi.zzk(1, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    public static final zzbfi<String> zzcV = zzbfi.zzk(1, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    public static final zzbfi<String> zzcW = zzbfi.zzk(1, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    public static final zzbfi<Integer> zzcX = zzbfi.zzh(1, "gads:drx_debug:timeout_ms", 5000);
    public static final zzbfi<Integer> zzcY = zzbfi.zzh(1, "gad:pixel_dp_comparision_multiplier", 1);
    public static final zzbfi<Boolean> zzcZ = zzbfi.zzg(1, "gad:interstitial_notify_publisher_without_delay", false);
    public static final zzbfi<Boolean> zzda = zzbfi.zzg(1, "gad:interstitial_for_multi_window", false);
    public static final zzbfi<Boolean> zzdb = zzbfi.zzg(1, "gad:interstitial_ad_stay_active_in_multi_window", false);
    public static final zzbfi<Boolean> zzdc = zzbfi.zzg(1, "gad:interstitial_multi_window_method", false);
    public static final zzbfi<Integer> zzdd = zzbfi.zzh(1, "gad:interstitial:close_button_padding_dip", 0);
    public static final zzbfi<Boolean> zzde = zzbfi.zzg(1, "gads:clearcut_logging:enabled", false);
    public static final zzbfi<Boolean> zzdf = zzbfi.zzg(1, "gads:clearcut_logging:write_to_file", false);
    public static final zzbfi<Boolean> zzdg = zzbfi.zzg(1, "gad:publisher_testing:force_local_request:enabled", true);
    public static final zzbfi<String> zzdh = zzbfi.zzk(1, "gad:publisher_testing:force_local_request:enabled_list", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<String> zzdi = zzbfi.zzk(1, "gad:publisher_testing:force_local_request:disabled_list", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Integer> zzdj = zzbfi.zzh(1, "gad:http_redirect_max_count:times", 8);
    public static final zzbfi<Boolean> zzdk = zzbfi.zzg(1, "gads:omid:enabled", true);
    public static final zzbfi<Integer> zzdl = zzbfi.zzh(1, "gads:omid:destroy_webview_delay", 1000);
    public static final zzbfi<Boolean> zzdm = zzbfi.zzg(1, "gads:omid_1_3_activate:enabled", false);
    public static final zzbfi<Boolean> zzdn = zzbfi.zzg(1, "gads:omid_1_3_create_html_session:enabled", false);
    public static final zzbfi<Boolean> zzdo = zzbfi.zzg(1, "gads:omid_1_3_create_js_session:enabled", false);
    public static final zzbfi<Boolean> zzdp = zzbfi.zzg(1, "gads:omid_1_3_friendly_obstruction:enabled", false);
    public static final zzbfi<Boolean> zzdq = zzbfi.zzg(1, "gads:omid_1_3_fire_loaded_event:enabled", false);
    public static final zzbfi<Boolean> zzdr = zzbfi.zzg(1, "gads:omid_use_admob_impl_dependency:enabled", false);
    public static final zzbfi<Boolean> zzds = zzbfi.zzg(1, "gads:nonagon:banner:enabled", true);
    public static final zzbfi<String> zzdt = zzbfi.zzk(1, "gads:nonagon:banner:ad_unit_exclusions", "(?!)");
    public static final zzbfi<Boolean> zzdu = zzbfi.zzg(1, "gads:nonagon:app_open:enabled", true);
    public static final zzbfi<Integer> zzdv = zzbfi.zzh(1, "gads:app_open_beta:min_version", 999999999);
    public static final zzbfi<Integer> zzdw = zzbfi.zzh(1, "gads:app_open_ad_open_beta_api:min_version", 202490999);
    public static final zzbfi<Boolean> zzdx = zzbfi.zzg(1, "gads:nonagon:app_open_app_switch_signal:enabled", false);
    public static final zzbfi<String> zzdy = zzbfi.zzk(1, "gads:nonagon:app_open:ad_unit_exclusions", "(?!)");
    public static final zzbfi<Boolean> zzdz = zzbfi.zzg(1, "gads:nonagon:interstitial:enabled", true);
    public static final zzbfi<String> zzdA = zzbfi.zzk(1, "gads:nonagon:interstitial:ad_unit_exclusions", "(?!)");
    public static final zzbfi<Boolean> zzdB = zzbfi.zzg(1, "gads:nonagon:rewardedvideo:enabled", true);
    public static final zzbfi<Boolean> zzdC = zzbfi.zzg(1, "gads:nonagon:mobile_ads_setting_manager:enabled", true);
    public static final zzbfi<String> zzdD = zzbfi.zzk(1, "gads:nonagon:rewardedvideo:ad_unit_exclusions", "(?!)");
    public static final zzbfi<Boolean> zzdE = zzbfi.zzg(1, "gads:nonagon:banner:check_dp_size", true);
    public static final zzbfi<Boolean> zzdF = zzbfi.zzg(1, "gads:nonagon:rewarded:load_multiple_ads", true);
    public static final zzbfi<Boolean> zzdG = zzbfi.zzg(1, "gads:nonagon:return_no_fill_error_code", false);
    public static final zzbfi<Boolean> zzdH = zzbfi.zzg(1, "gads:nonagon:continue_on_no_fill", false);
    public static final zzbfi<Boolean> zzdI = zzbfi.zzg(1, "gads:nonagon:separate_timeout:enabled", true);
    public static final zzbfi<Integer> zzdJ = zzbfi.zzh(1, "gads:nonagon:request_timeout:seconds", 60);
    public static final zzbfi<Boolean> zzdK = zzbfi.zzg(1, "gads:nonagon:banner_recursive_renderer", false);
    public static final zzbfi<Boolean> zzdL = zzbfi.zzg(1, "gads:nonagon:app_stats_lock:enabled", false);
    public static final zzbfi<Boolean> zzdM = zzbfi.zzg(1, "gads:nonagon:app_stats_main_thread:enabled", false);
    public static final zzbfi<Boolean> zzdN = zzbfi.zzg(1, "gads:uri_query_to_map_bg_thread:enabled", false);
    public static final zzbfi<String> zzdO = zzbfi.zzk(1, "gads:uri_query_to_map_bg_thread:types", "/result");
    public static final zzbfi<Integer> zzdP = zzbfi.zzh(1, "gads:uri_query_to_map_bg_thread:min_length", 1000);
    public static final zzbfi<Boolean> zzdQ = zzbfi.zzg(1, "gads:nonagon:active_view_gmsg_background_thread:enabled", true);
    public static final zzbfi<Boolean> zzdR = zzbfi.zzg(1, "gads:active_view_gmsg_separate_pool:enabled", true);
    public static final zzbfi<Boolean> zzdS = zzbfi.zzg(1, "gads:active_view_audio_signal_audio_mode:enabled", false);
    public static final zzbfi<Boolean> zzdT = zzbfi.zzg(1, "gads:signals:ad_id_info:enabled", false);
    public static final zzbfi<Boolean> zzdU = zzbfi.zzg(1, "gads:signals:app_index:enabled", false);
    public static final zzbfi<Boolean> zzdV = zzbfi.zzg(1, "gads:signals:attestation_token:enabled", false);
    public static final zzbfi<Boolean> zzdW = zzbfi.zzg(1, "gads:signals:cache:enabled", false);
    public static final zzbfi<Boolean> zzdX = zzbfi.zzg(1, "gads:signals:doritos:enabled", false);
    public static final zzbfi<Boolean> zzdY = zzbfi.zzg(1, "gads:signals:doritos:v1:enabled", false);
    public static final zzbfi<Boolean> zzdZ = zzbfi.zzg(1, "gads:signals:doritos:v2:immediate:enabled", false);
    public static final zzbfi<Boolean> zzea = zzbfi.zzg(1, "gads:signals:parental_control:enabled", false);
    public static final zzbfi<Boolean> zzeb = zzbfi.zzg(1, "gads:signals:video_decoder:enabled", false);
    public static final zzbfi<Boolean> zzec = zzbfi.zzg(1, "gads:signals:banner_hardware_acceleration:enabled", false);
    public static final zzbfi<Boolean> zzed = zzbfi.zzg(1, "gads:signals:native_hardware_acceleration:enabled", false);
    public static final zzbfi<Boolean> zzee = zzbfi.zzg(1, "gads:attestation_token:enabled", false);
    public static final zzbfi<Long> zzef = zzbfi.zzi(1, "gads:mobius_linking:sdk_side_cooldown_time_threshold:ms", 3600000);
    public static final zzbfi<Integer> zzeg = zzbfi.zzh(1, "gads:adoverlay:b68684796:targeting_sdk:lower_bound", 27);
    public static final zzbfi<Integer> zzeh = zzbfi.zzh(1, "gads:adoverlay:b68684796:targeting_sdk:upper_bound", 26);
    public static final zzbfi<Integer> zzei = zzbfi.zzh(1, "gads:adoverlay:b68684796:sdk_int:lower_bound", 27);
    public static final zzbfi<Integer> zzej = zzbfi.zzh(1, "gads:adoverlay:b68684796:sdk_int:upper_bound", 26);
    public static final zzbfi<Boolean> zzek = zzbfi.zzg(1, "gads:consent:shared_preference_reading:enabled", true);
    public static final zzbfi<Boolean> zzel = zzbfi.zzg(1, "gads:consent:iab_consent_info:enabled", true);
    public static final zzbfi<Boolean> zzem = zzbfi.zzg(1, "gads:fc_consent:shared_preference_reading:enabled", true);
    public static final zzbfi<String> zzen = zzbfi.zzk(1, "gads:sp:json_string", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Boolean> zzeo = zzbfi.zzg(1, "gads:nativeads:image:sample:enabled", true);
    public static final zzbfi<Integer> zzep = zzbfi.zzh(1, "gads:nativeads:image:sample:pixels", 1048576);
    public static final zzbfi<Boolean> zzeq = zzbfi.zzg(1, "gads:nativeads:pub_image_scale_type:enabled", true);
    public static final zzbfi<Boolean> zzer = zzbfi.zzg(1, "gads:offline_signaling:enabled", false);
    public static final zzbfi<Integer> zzes = zzbfi.zzh(1, "gads:offline_signaling:log_maximum", 100);
    public static final zzbfi<Boolean> zzet = zzbfi.zzg(1, "gads:nativeads:template_signal:enabled", true);
    public static final zzbfi<Boolean> zzeu = zzbfi.zzg(1, "gads:nativeads:media_content_aspect_ratio:enabled", true);
    public static final zzbfi<Boolean> zzev = zzbfi.zzg(1, "gads:nativeads:media_content_metadata:enabled", true);
    public static final zzbfi<Boolean> zzew = zzbfi.zzg(1, "gads:predictive_prefetch_from_cld:enabled", false);
    public static final zzbfi<Boolean> zzex = zzbfi.zzg(1, "gads:precache_pool:verbose_logging", false);
    public static final zzbfi<Integer> zzey = zzbfi.zzh(1, "gads:rewarded_precache_pool:count", 0);
    public static final zzbfi<Integer> zzez = zzbfi.zzh(1, "gads:interstitial_precache_pool:count", 0);
    public static final zzbfi<String> zzeA = zzbfi.zzk(1, "gads:rewarded_precache_pool:discard_strategy", "lru");
    public static final zzbfi<String> zzeB = zzbfi.zzk(1, "gads:interstitial_precache_pool:discard_strategy", "lru");
    public static final zzbfi<String> zzeC = zzbfi.zzk(1, "gads:rewarded_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzbfi<String> zzeD = zzbfi.zzk(1, "gads:interstitial_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzbfi<Integer> zzeE = zzbfi.zzh(1, "gads:rewarded_precache_pool:size", 1);
    public static final zzbfi<Integer> zzeF = zzbfi.zzh(1, "gads:interstitial_precache_pool:size", 1);
    public static final zzbfi<Integer> zzeG = zzbfi.zzh(1, "gads:rewarded_precache_pool:ad_time_limit", 1200);
    public static final zzbfi<Integer> zzeH = zzbfi.zzh(1, "gads:interstitial_precache_pool:ad_time_limit", 1200);
    public static final zzbfi<String> zzeI = zzbfi.zzk(1, "gads:rewarded_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzbfi<String> zzeJ = zzbfi.zzk(1, "gads:interstitial_precache_pool:schema", "customTargeting,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzbfi<String> zzeK = zzbfi.zzk(1, "gads:app_open_precache_pool:schema", "orientation,npa,tagForChildDirectedTreatment,tagForUnderAgeOfConsent,maxAdContentRating");
    public static final zzbfi<String> zzeL = zzbfi.zzk(1, "gads:app_open_precache_pool:discard_strategy", "oldest");
    public static final zzbfi<Integer> zzeM = zzbfi.zzh(1, "gads:app_open_precache_pool:count", 0);
    public static final zzbfi<String> zzeN = zzbfi.zzk(1, "gads:app_open_precache_pool:cache_start_trigger", "onAdClosed");
    public static final zzbfi<Integer> zzeO = zzbfi.zzh(1, "gads:app_open_precache_pool:size", 1);
    public static final zzbfi<Integer> zzeP = zzbfi.zzh(1, "gads:app_open_precache_pool:ad_time_limit", 14400);
    public static final zzbfi<Boolean> zzeQ = zzbfi.zzg(1, "gads:memory_leak:b129558083", false);
    public static final zzbfi<Boolean> zzeR = zzbfi.zzg(1, "gads:unhandled_event_reporting:enabled", false);
    public static final zzbfi<Boolean> zzeS = zzbfi.zzg(1, "gads:response_info:enabled", true);
    public static final zzbfi<Boolean> zzeT = zzbfi.zzg(1, "gads:csi:interstitial_failed_to_show:enabled", false);
    public static final zzbfi<Boolean> zzeU = zzbfi.zzg(1, "gads:csi:mediation_failure:enabled", false);
    public static final zzbfi<String> zzeV = zzbfi.zzk(1, "gads:csi:error_parsing:regex", "^(\\d+)");
    public static final zzbfi<Boolean> zzeW = zzbfi.zzg(1, "gads:csi:eids_from_cld:enabled", false);
    public static final zzbfi<Boolean> zzeX = zzbfi.zzg(1, "gads:request_id_check:enabled", false);
    public static final zzbfi<Boolean> zzeY = zzbfi.zzg(1, "gads:request_id_int32:enabled", true);
    public static final zzbfi<Boolean> zzeZ = zzbfi.zzg(1, "gads:render_decouple:enabled", true);
    public static final zzbfi<Integer> zzfa = zzbfi.zzh(1, "gads:maximum_query_json_cache_size", 200);
    public static final zzbfi<Long> zzfb = zzbfi.zzi(1, "gads:timeout_query_json_cache:millis", 3600000);
    public static final zzbfi<Boolean> zzfc = zzbfi.zzg(1, "gads:signal_collection_without_rendering:enabled", true);
    public static final zzbfi<Integer> zzfd = zzbfi.zzh(1, "gads:native_ads_signal:timeout", 1000);
    public static final zzbfi<Boolean> zzfe = zzbfi.zzg(2, "DISABLE_CRASH_REPORTING", false);
    public static final zzbfi<Boolean> zzff = zzbfi.zzg(1, "gads:paid_event_listener:enabled", true);
    public static final zzbfi<Boolean> zzfg = zzbfi.zzg(1, "gads:interscroller_ad:enabled", true);
    public static final zzbfi<Boolean> zzfh = zzbfi.zzg(1, "gads:interscroller_ad:refresh:enabled", false);
    public static final zzbfi<Integer> zzfi = zzbfi.zzh(1, "gads:interscroller:min_width", 300);
    public static final zzbfi<Integer> zzfj = zzbfi.zzh(1, "gads:interscroller:min_height", ItemTouchHelper.Callback.DEFAULT_SWIPE_ANIMATION_DURATION);
    public static final zzbfi<Boolean> zzfk = zzbfi.zzg(1, "gads:is_in_scroll_view_new_api:enabled", true);
    public static final zzbfi<Boolean> zzfl = zzbfi.zzg(1, "gads:policy_validator_for_all_pubs:enabled", true);
    public static final zzbfi<String> zzfm = zzbfi.zzk(1, "gad:publisher_testing:policy_validator:enabled_list", RequestConfiguration.MAX_AD_CONTENT_RATING_UNSPECIFIED);
    public static final zzbfi<Integer> zzfn = zzbfi.zzh(1, "gads:policy_validator_layoutparam:flags", 808);
    public static final zzbfi<Boolean> zzfo = zzbfi.zzg(2, "NATIVE_AD_DEBUGGER_ENABLED", true);
    public static final zzbfi<Integer> zzfp = zzbfi.zzh(1, "gads:policy_validator_overlay_width:dp", 350);
    public static final zzbfi<Integer> zzfq = zzbfi.zzh(1, "gads:policy_validator_overlay_height:dp", 140);
    public static final zzbfi<Boolean> zzfr = zzbfi.zzg(1, "gads:use_wide_viewport:enabled", false);
    public static final zzbfi<Boolean> zzfs = zzbfi.zzg(1, "gads:load_with_overview_mode:enabled", false);
    public static final zzbfi<Boolean> zzft = zzbfi.zzg(1, "gads:wire_banner_listener_after_request:enabled", false);
    public static final zzbfi<Boolean> zzfu = zzbfi.zzg(1, "gads:wire_app_open_listener_after_request:enabled", false);
    public static final zzbfi<Boolean> zzfv = zzbfi.zzg(1, "gads:wire_interstitial_listener_after_request:enabled", false);
    public static final zzbfi<String> zzfw = zzbfi.zzk(1, "gads:server_transaction_source:list", "Network");
    public static final zzbfi<Boolean> zzfx = zzbfi.zzg(1, "gads:can_open_app_and_open_app_action:enabled", false);
    public static final zzbfi<Boolean> zzfy = zzbfi.zzg(1, "gads:open_gmsg:set_uri_data_and_type:enabled", false);
    public static final zzbfi<Integer> zzfz = zzbfi.zzh(1, "gads:ad_error_api:min_version", 202006000);
    public static final zzbfi<Boolean> zzfA = zzbfi.zzg(1, "gads:forward_bow_error_string:enabled", true);
    public static final zzbfi<Boolean> zzfB = zzbfi.zzg(1, "gads:continue_on_process_response:enabled", false);
    public static final zzbfi<Boolean> zzfC = zzbfi.zzg(1, "gads:mediation_status_reporting:enabled", true);
    public static final zzbfi<Integer> zzfD = zzbfi.zzh(1, "gads:mediation_no_fill_error:min_version", 999999999);
    public static final zzbfi<Integer> zzfE = zzbfi.zzh(1, "gads:offline_database_version:version", 1);
    public static final zzbfi<Boolean> zzfF = zzbfi.zzg(1, "gads:offline_ads_notification:enabled", true);
    public static final zzbfi<Boolean> zzfG = zzbfi.zzg(1, "gads:use_new_network_api:enabled", true);
    public static final zzbfi<Boolean> zzfH = zzbfi.zzg(1, "gads:handle_click_recorded_event:enabled", false);
    public static final zzbfi<Boolean> zzfI = zzbfi.zzg(1, "gads:default_network_type_fine_to_unknown:enabled", true);
    public static final zzbfi<Boolean> zzfJ = zzbfi.zzg(1, "gads:handle_intent_async:enabled", false);
    public static final zzbfi<Boolean> zzfK = zzbfi.zzg(1, "gads:skip_deep_link_validation_native_ads:enabled", false);
    public static final zzbfi<Boolean> zzfL = zzbfi.zzg(1, "gads:try_deep_link_fallback_native_ads:enabled", false);
    public static final zzbfi<Boolean> zzfM = zzbfi.zzg(1, "gads:in_app_link_handling_for_android_11_enabled:enabled", false);
    public static final zzbfi<Boolean> zzfN = zzbfi.zzg(1, "gads:new_remote_logging_utils:enabled", false);
    public static final zzbfi<Boolean> zzfO = zzbfi.zzg(1, "gads:remote_logging:enabled", false);
    public static final zzbfi<Integer> zzfP = zzbfi.zzh(1, "gads:remote_log_send_rate_ms", 60000);
    public static final zzbfi<Integer> zzfQ = zzbfi.zzh(1, "gads:remote_log_queue_max_entries", 500);
    public static final zzbfi<Integer> zzfR = zzbfi.zzh(1, "gads:app_event_queue_size", 20);
    public static final zzbfi<Boolean> zzfS = zzbfi.zzg(1, "gads:hide_grey_title_bar:enabled", false);
    public static final zzbfi<Boolean> zzfT = zzbfi.zzg(1, "gads:interstitial_ad_parameter_handler:enabled", false);
    public static final zzbfi<Boolean> zzfU = zzbfi.zzg(1, "gads:inspector:enabled", true);
    public static final zzbfi<String> zzfV = zzbfi.zzk(1, "gads:inspector:ui_url", "https://admob-gmats.uc.r.appspot.com/");
    public static final zzbfi<Integer> zzfW = zzbfi.zzh(1, "gads:inspector:max_ad_life_cycles", 1000);
    public static final zzbfi<Integer> zzfX = zzbfi.zzh(1, "gads:inspector:ui_invocation_millis", 2000);
    public static final zzbfi<Boolean> zzfY = zzbfi.zzg(1, "gads:inspector:shake_enabled", true);
    public static final zzbfi<Float> zzfZ = zzbfi.zzj(1, "gads:inspector:shake_strength", 2.0f);
    public static final zzbfi<Integer> zzga = zzbfi.zzh(1, "gads:inspector:shake_interval", 500);
    public static final zzbfi<Integer> zzgb = zzbfi.zzh(1, "gads:inspector:shake_reset_time_ms", PathInterpolatorCompat.MAX_NUM_POINTS);
    public static final zzbfi<Integer> zzgc = zzbfi.zzh(1, "gads:inspector:shake_count", 3);
    public static final zzbfi<Boolean> zzgd = zzbfi.zzg(1, "gads:inspector:flick_enabled", true);
    public static final zzbfi<Float> zzge = zzbfi.zzj(1, "gads:inspector:flick_rotation_threshold", 45.0f);
    public static final zzbfi<Integer> zzgf = zzbfi.zzh(1, "gads:inspector:flick_reset_time_ms", PathInterpolatorCompat.MAX_NUM_POINTS);
    public static final zzbfi<Integer> zzgg = zzbfi.zzh(1, "gads:inspector:flick_count", 2);
    public static final zzbfi<Integer> zzgh = zzbfi.zzh(1, "gads:inspector:icon_width_px", 256);
    public static final zzbfi<Integer> zzgi = zzbfi.zzh(1, "gads:inspector:icon_height_px", 256);
    public static final zzbfi<Boolean> zzgj = zzbfi.zzg(1, "gads:inspector:ad_manager_enabled", true);
    public static final zzbfi<Boolean> zzgk = zzbfi.zzg(1, "gads:inspector:policy_violations_enabled", false);
    public static final zzbfi<Boolean> zzgl = zzbfi.zzg(1, "gads:inspector:bidding_data_enabled", false);
    public static final zzbfi<Boolean> zzgm = zzbfi.zzg(1, "gads:paw_register_webview:enabled", true);
    public static final zzbfi<Boolean> zzgn = zzbfi.zzg(1, "gads:h5ads:enabled", true);
    public static final zzbfi<Integer> zzgo = zzbfi.zzh(1, "gads:h5ads:max_num_ad_objects", 10);
    public static final zzbfi<Integer> zzgp = zzbfi.zzh(1, "gads:h5ads:max_gmsg_length", 5000);
    public static final zzbfi<String> zzgq = zzbfi.zzk(1, "gads:h5ads:afma_prefix", "(window.AFMA_ReceiveMessage || window.h5_iframe.contentWindow.AFMA_ReceiveMessage || function() {})");
    public static final zzbfi<Boolean> zzgr = zzbfi.zzg(1, "gads:native_html_video_asset:enabled", false);
    public static final zzbfi<Boolean> zzgs = zzbfi.zzg(1, "gads:native_html_image_asset:enabled", false);
    public static final zzbfi<Boolean> zzgt = zzbfi.zzg(1, "gads:custom_gesture_disable_media_view", true);
    public static final zzbfi<Boolean> zzgu = zzbfi.zzg(1, "gads:leibniz:events:enabled", false);
    public static final zzbfi<Boolean> zzgv = zzbfi.zzg(1, "gads:msa:alphavis_enabled", false);
    public static final zzbfi<Boolean> zzgw = zzbfi.zzg(1, "gads:msa:adutilalphavis_enabled", false);
    public static final zzbfi<Boolean> zzgx = zzbfi.zzg(1, "gads:msa:nativealphavis_enabled", false);
    public static final zzbfi<Integer> zzgy = zzbfi.zzh(1, "gads:msa:visminalpha", 90);

    public static void zza(final Context context) {
        zzbfs.zza(new zzffb(context) { // from class: com.google.android.gms.internal.ads.zzbfp
            private final Context zza;

            /* JADX INFO: Access modifiers changed from: package-private */
            {
                this.zza = context;
            }

            @Override // com.google.android.gms.internal.ads.zzffb
            public final Object zza() {
                Context context2 = this.zza;
                zzbfi<String> zzbfiVar = zzbfq.zza;
                zzbba.zzc().zza(context2);
                return null;
            }
        });
    }

    public static void zzb(Context context, int i, JSONObject jSONObject) {
        zzbba.zza();
        SharedPreferences.Editor edit = zzbfk.zza(context).edit();
        zzbba.zzb();
        zzbgs<Boolean> zzbgsVar = zzbgw.zza;
        zzbba.zzb().zzc(edit, 1, jSONObject);
        zzbba.zza();
        edit.commit();
    }

    public static List<String> zzc() {
        return zzbba.zzb().zzd();
    }

    public static List<String> zzd() {
        return zzbba.zzb().zze();
    }
}
